ArchLinuxScripts/
     __init__.py
     changeDefaultWallpaper.py
     InternetSharing/
          __init__.py
          DHCP/
                    __init__.py
                    dhcp_internet_sharing.py
                    ...
          ...
     English/
          __init__.py
          Words/
                    __init__.py
                    guess_the_word.py
                    ...
          ...
     Plasma/
          __init__.py
          PlasmaWidgets/
                    __init__.py
               curriences_rates/
                              __init__.py
                              currencies_rates.py
                              ...
                    ...
          ...
     Security/
          __init__.py
          analyzeTcpTraffic.py
          printVulnerablePackages.py
          Parse/
                    TcpPacket.py
                    __init__.py
                    ...
          Package/
                    __init__.py
                    package.py
                    ...
          DB/
                    __init__.py
                    connectionDB.py
                    sqliteWrapper.py
                    sqlite_test.py
                    ...
          SSH/
                    __init__.py
                    killRemoteProcessOverSSH.py
                    ...
          ...
     Hardware/
          __init__.py
          disableTrackPoint.py
          enableTrackPoint.py
          ...
     SpeechCommnads/
          __init__.py
          speech_recognition_background.py
          speech_recognition_exec_command.py
          test_mic.py
          ...
     Python/
          __init__.py
          DirectoryStructure/
                    CreateDirectoryStructure.py
                    Directory.py
                    File.py
                    FileManager.py
                    __init__.py
                    ...
          ...
     Package/
          __init__.py
          package.py
          ...
     Network/
          __init__.py
          change_mac_address_permanently_2_doesnt_work.py
          change_mac_address_permanently_doesnt_work.py
          NetworkActivityOfProcess/
                    NetworkActivityOfProcess.py
                    __init__.py
                    ...
          ...
     Facebook/
          __init__.py
          facebookGetFriendsNames.py
          facebookLogin.py
          ...
     Systemd/
          __init__.py
          make_binary_to_start_on_boot_time.py
          ...
     ClientServer/
          __init__.py
          FileTransfer/
                    __init__.py
                    client.py
                    server.py
                    ...
          ...
     Find/
          __init__.py
          FindFileByMD5Sum/
                    __init__.py
                    findFileByMD5Sum.py
                    ...
          FindFileBySHA256Sum/
                    __init__.py
                    findFileBySHA256Sum.py
                    ...
          ...
     Logs/
          __init__.py
          Xorg/
                    __init__.py
                    analyzeXorg.py
                    ...
          SDDM/
                    __init__.py
                    analyzeSDDM.py
                    ...
          ...
     Scraping/
          __init__.py
          scrapingUserCommentsDnesBg.py
          WebSpider/
                    ScrapingEmailAddresses.py
                    ScrapingUniqueWords.py
                    ScrapingWords.py
                    Spider.py
                    StorageData.py
                    StorageUniqueData.py
                    __init__.py
                    ...
          ...
     Bots/
          __init__.py
          eKingdomFarmingGold/
                    EKingdomFarmingGold.py
                    __init__.py
                    ...
          eToroBot/
                    __init__.py
                    eToroBot.py
                    ...
          NeverwinterProfessionCraft/
                    NeverwinterProfessionCrafting.py
                    __init__.py
                    ...
          ...
