ArchLinuxScripts/
     __init__.py
     changeDefaultWallpaper.py
     Bots/Nearby_social_network_prop_bot/
          NearbyPropBot.py
          ...
     Bots/NeverwinterProfessionCraft/
          NeverwinterProfessionCrafting.py
          ...
     Bots/eKingdomFarmingGold/
          EKingdomFarmingGold.py
          ...
     Bots/eToroBot/
          eToroBot.py
          ...
     ClientServer/FileTransfer/
          server.py
          client.py
          ...
     English/Words/
          guess_the_word.py
          ...
     Facebook/
          facebookGetFriendsNames.py
          facebookLogin.py
          ...
     Find/FindFileByMD5Sum/
          findFileByMD5Sum.py
          ...
     Find/FindFileBySHA256Sum/
          findFileBySHA256Sum.py
          ...
     Hardware/
          disableTrackPoint.py
          enableTrackPoint.py
          ...
     InternetSharing/DHCP/
          dhcp_internet_sharing.py
          ...
     Logs/SDDM/
          analyzeSDDM.py
          ...
     Logs/Xorg/
          analyzeXorg.py
          ...
     Network/
          change_mac_address_permanently_2_doesnt_work.py
          change_mac_address_permanently_doesnt_work.py
          ...
     Network/NetworkActivityOfProcess/
          NetworkActivityOfProcess.py
          ...
     Package/
          package.py
          __init__.py
          ...
     Plasma/PlasmaWidgets/curriences_rates/
          currencies_rates.py
          ...
     Python/
          createDirectoryStructure.py
          ...
     Scraping/
          scrapingUserCommentsDnesBg.py
          ...
     Scraping/WebSpider/
          ScrapingUniqueWords.py
          Spider.py
          StorageUniqueData.py
          StorageData.py
          ScrapingWords.py
          ScrapingEmailAddresses.py
          ...
     Security/
          analyzeTcpTraffic.py
          printVulnerablePackages.py
          ...
     Security/DB/
          connectionDB.py
          sqliteWrapper.py
          sqlite_test.py
          __init__.py
          ...
     Security/Package/
          package.py
          __init__.py
          ...
     Security/Parse/
          TcpPacket.py
          __init__.py
          ...
     Security/SSH/
          killRemoteProcessOverSSH.py
          ...
     SpeechCommnads/
          speech_recognition_exec_command.py
          test_mic.py
          speech_recognition_background.py
          ...
     Systemd/
          make_binary_to_start_on_boot_time.py
          ...
