ArchLinuxScripts/
     __init__.py
     changeDefaultWallpaper.py
     InternetSharing/
          DHCP/
                    dhcp_internet_sharing.py
                    ...
          ...
     English/
          Words/
                    guess_the_word.py
                    ...
          ...
     Plasma/
          PlasmaWidgets/
               curriences_rates/
                              currencies_rates.py
                              ...
                    ...
          ...
     Security/
          analyzeTcpTraffic.py
          printVulnerablePackages.py
          Parse/
                    TcpPacket.py
                    __init__.py
                    ...
          Package/
                    package.py
                    __init__.py
                    ...
          DB/
                    connectionDB.py
                    sqliteWrapper.py
                    sqlite_test.py
                    __init__.py
                    ...
          SSH/
                    killRemoteProcessOverSSH.py
                    ...
          ...
     Hardware/
          disableTrackPoint.py
          enableTrackPoint.py
          ...
     SpeechCommnads/
          speech_recognition_exec_command.py
          test_mic.py
          speech_recognition_background.py
          ...
     Python/
          createDirectoryStructure.py
          ...
     Package/
          package.py
          __init__.py
          ...
     Network/
          change_mac_address_permanently_2_doesnt_work.py
          change_mac_address_permanently_doesnt_work.py
          NetworkActivityOfProcess/
                    NetworkActivityOfProcess.py
                    ...
          ...
     Facebook/
          facebookGetFriendsNames.py
          facebookLogin.py
          ...
     Systemd/
          make_binary_to_start_on_boot_time.py
          ...
     ClientServer/
          FileTransfer/
                    server.py
                    client.py
                    ...
          ...
     Find/
          FindFileByMD5Sum/
                    findFileByMD5Sum.py
                    ...
          FindFileBySHA256Sum/
                    findFileBySHA256Sum.py
                    ...
          ...
     Logs/
          Xorg/
                    analyzeXorg.py
                    ...
          SDDM/
                    analyzeSDDM.py
                    ...
          ...
     Scraping/
          scrapingUserCommentsDnesBg.py
          WebSpider/
                    ScrapingUniqueWords.py
                    Spider.py
                    StorageUniqueData.py
                    StorageData.py
                    ScrapingWords.py
                    ScrapingEmailAddresses.py
                    ...
          ...
     Bots/
          eKingdomFarmingGold/
                    EKingdomFarmingGold.py
                    ...
          eToroBot/
                    eToroBot.py
                    ...
          Nearby_social_network_prop_bot/
                    NearbyPropBot.py
                    ...
          NeverwinterProfessionCraft/
                    NeverwinterProfessionCrafting.py
                    ...
          ...
